# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
""


Job.create!(name: "front end stuff", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, lorem vel commodo vehicula, sapien mauris auctor dolor, eu tempus neque velit vel est. Nullam a efficitur velit, sit amet facilisis arcu. Etiam rhoncus eleifend posuere. Praesent vulputate euismod ex,")
Job.create!(name: "back end stuff", description: " sed pellentesque ante venenatis eu. Proin porttitor aliquet ante, eget scelerisque magna pellentesque at. Etiam congue, risus eu aliquam congue, ligula leo efficitur lectus, nec finibus ante ante eu elit. Fusce at porta est. Sed placerat finibus ante eu lobortis. Nulla facilisi. Phasellus fermentum magna nunc, in finibus lorem maximus id. Nulla dolor dolor, consequat nec dolor sed, rutrum sollicitudin velit.")
Job.create!(name: "whatev end stuff", description: " sed pellentesque ante venenatis eu. Proin porttitor aliquet ante, eget scelerisque magna pellentesque at. Etiam congue, risus eu aliquam congue, ligula leo efficitur lectus, nec finibus ante ante eu elit. Fusce at porta est. Sed placerat finibus ante eu lobortis. Nulla facilisi. Phasellus fermentum magna nunc, in finibus lorem maximus id. Nulla dolor dolor, consequat nec dolor sed, rutrum sollicitudin velit.")
Job.create!(name: "ceo end stuff", description: " sed pellentesque ante venenatis eu. Proin porttitor aliquet ante, eget scelerisque magna pellentesque at. Etiam congue, risus eu aliquam congue, ligula leo efficitur lectus, nec finibus ante ante eu elit. Fusce at porta est. Sed placerat finibus ante eu lobortis. Nulla facilisi. Phasellus fermentum magna nunc, in finibus lorem maximus id. Nulla dolor dolor, consequat nec dolor sed, rutrum sollicitudin velit.")
Job.create!(name: "ceo stuff", description: " sed pellentesque ante venenatis eu. Proin porttitor aliquet ante, eget scelerisque magna pellentesque at. Etiam congue, risus eu aliquam congue, ligula leo efficitur lectus, nec finibus ante ante eu elit. Fusce at porta est. Sed placerat finibus ante eu lobortis. Nulla facilisi. Phasellus fermentum magna nunc, in finibus lorem maximus id. Nulla dolor dolor, consequat nec dolor sed, rutrum sollicitudin velit.")
Job.create!(name: "cto stuff", description: " sed pellentesque ante venenatis eu. Proin porttitor aliquet ante, eget scelerisque magna pellentesque at. Etiam congue, risus eu aliquam congue, ligula leo efficitur lectus, nec finibus ante ante eu elit. Fusce at porta est. Sed placerat finibus ante eu lobortis. Nulla facilisi. Phasellus fermentum magna nunc, in finibus lorem maximus id. Nulla dolor dolor, consequat nec dolor sed, rutrum sollicitudin velit.")
Job.create!(name: "fron stuff", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, lorem vel commodo vehicula, sapien mauris auctor dolor, eu tempus neque velit vel est. Nullam a efficitur velit, sit amet facilisis arcu. Etiam rhoncus eleifend posuere. Praesent vulputate euismod ex,")
Job.create!(name: "frond end stuff", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, lorem vel commodo vehicula, sapien mauris auctor dolor, eu tempus neque velit vel est. Nullam a efficitur velit, sit amet facilisis arcu. Etiam rhoncus eleifend posuere. Praesent vulputate euismod ex,")
Job.create!(name: "front  stuff", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, lorem vel commodo vehicula, sapien mauris auctor dolor, eu tempus neque velit vel est. Nullam a efficitur velit, sit amet facilisis arcu. Etiam rhoncus eleifend posuere. Praesent vulputate euismod ex,")
Job.create!(name: "front of house stuff", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tincidunt, lorem vel commodo vehicula, sapien mauris auctor dolor, eu tempus neque velit vel est. Nullam a efficitur velit, sit amet facilisis arcu. Etiam rhoncus eleifend posuere. Praesent vulputate euismod ex")
